### ISSUE TITLE
Blurry

### ISSUE THREAD

**Issue by Manueldjz** [zhigang1992/ZGExpandZoomView#1]
any idea for... imageView... with blur like cover photo in twitter
Thanks

**Comment by zhigang1992** [comment]
This project is actually really simple, it's more of a way of explaining how it works rather than providing a framework or tools.
The key here is `contentMode` set to `UIViewContentModeScaleToFill`, and you can do it work any view. not just a `UIImageView`.
With that, what you're looking for is a live blurring framework.
Try this `https://github.com/nicklockwood/FXBlurView`, 
Good luck. :)
